-- EDA
SELECT * FROM categories; 
SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM order_items;
SELECT * FROM orders;
SELECT * FROM payments;
SELECT * FROM products;
SELECT * FROM sellers;
SELECT * FROM shipping;



SELECT * 
FROM shipping
WHERE order_id = 34


-- order_id = 22

SELECT *
FROM orders
WHERE order_id = 22 -- 2024-09-10

SELECT * 
FROM payments
WHERE order_id = 22

SELECT * 
FROM shipping
WHERE order_id = 22

-- EDA END


-- ----------------------------
-- Business Problems 
-- Advance Analysis 
-- ----------------------------



/*
Question 1: Top Selling Products
			Query the top 10 products by total sales value. 
Challenge: 	Include product name, total quantity sold, and total sales value.
*/

SElECT
	p.product_id,
	p.product_name, 
	TO_CHAR(SUM(oi.quantity), 'FM999,999,999,990.00') as Quantity, 
	TO_CHAR(SUM(oi.total_price), 'FM999,999,999,990.00') as Total_Sales_Value
	
FROM order_items as oi
JOIN products as p ON oi.product_id = p.product_id
JOIN orders as o ON oi.order_id = o.order_id
WHERE o.order_status = 'completed'
GROUP BY p.product_name, p.product_id
ORDER BY Total_Sales_Value DESC
LIMIT 10;



/*
Question 2: Revenue by Category
			Calculate the total revenue generated by each product category. 
Challenge: 	Include the percentage contribution of each category to total revenue.
*/



SELECT 
	c.category_id,
	c.category_name,
	TO_CHAR(SUM(oi.total_price), 'FM999,999,999,999.00') as Total_Revenue,
	TO_CHAR(SUM(oi.total_price) / 
			(SELECT SUM(total_price) FROM order_items) * 100, 'FM999,990.00%')
			AS Percentage

FROM products as p
JOIN order_items as oi ON p.product_id = oi.product_id
JOIN categories as c ON p.category_id = c.category_id
GROUP BY c.category_name, c.category_id
ORDER BY Total_Revenue DESC



/*
Question 3: Average Order Value (AOV)
			Calculate the average order value for each customer. 
Challenge: 	Include only customers with more than 100 orders.
*/

SELECT 
	cs.customer_id as Customer_id,
	CONCAT(cs.first_name, ' ',cs.last_name) as Customer,
	COUNT (DISTINCT(o.order_id)) as num_orders,
	TO_CHAR(SUM(oi.total_price)/COUNT(DISTINCT(o.order_id)), 'FM999,999,999,999.00') as AOV
	
FROM orders as o
JOIN customers as cs ON o.customer_id =cs.customer_id
JOIN order_items as oi ON o.order_id = oi.order_id
GROUP BY 1,2
HAVING COUNT (DISTINCT(o.order_id))  > 35
ORDER BY AOV DESC



/*
Question 4: 
			Query the top 10 products by total sales value. 
Challenge: 	Include product name, total quantity sold, and total sales value.
*/














/*
Question 5: 
			Query the top 10 products by total sales value. 
Challenge: 	Include product name, total quantity sold, and total sales value.
*/
